"use client"
import "./globals.css";

import { useState } from 'react';
import { LoginPage } from '@/components/ui/LoginPage';
import { Sidebar } from '@/components/ui/SidebarFigma';
import { TopBar } from '@/components/ui/TopBar';
import { Dashboard } from '@/components/ui/Dashboard';
import { NewExtraction } from '@/components/ui/NewExtraction';
import { History } from '@/components/ui/History';
import { Analytics } from '@/components/ui/Analytics';
import { Download } from '@/components/ui/Download';
import { Settings } from '@/components/ui/Settings';

type Page = 'dashboard' | 'new-extraction' | 'history' | 'analytics' | 'download' | 'settings';

export default function App() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const [currentPage, setCurrentPage] = useState<Page>('dashboard');
  const [username, setUsername] = useState('Putra Azam');

  const handleLogin = () => {
    setIsLoggedIn(true);
  };

  const handleLogout = () => {
    setIsLoggedIn(false);
    setCurrentPage('dashboard');
  };

  if (!isLoggedIn) {
    return <LoginPage onLogin={handleLogin} />;
  }

  const pageConfig = {
    'dashboard': { title: 'Dashboard', component: Dashboard },
    'new-extraction': { title: 'New Extraction', component: NewExtraction },
    'history': { title: 'Extraction History', component: History },
    'analytics': { title: 'Analytics', component: Analytics },
    'download': { title: 'Downloads', component: Download },
    'settings': { title: 'Settings', component: Settings },
  };

  const CurrentPageComponent = pageConfig[currentPage].component;

  return (
    <html lang='en' >
      <body>
     <div className="flex h-screen bg-gray-50">
      <Sidebar 
        currentPage={currentPage} 
        onNavigate={setCurrentPage} 
        username={username}
        onLogout={handleLogout}
      />
      <div className="flex-1 flex flex-col overflow-hidden">
        <TopBar title={pageConfig[currentPage].title} />
        <main className="flex-1 overflow-y-auto p-8">
          <CurrentPageComponent 
            onNavigate={setCurrentPage}
            username={username}
            onUpdateUsername={setUsername}
          />
        </main>
      </div>
    </div>       
      </body>

    </html>

  );
}



// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
// import { AppSidebar } from "@/components/app-sidebar";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body>
//       <SidebarProvider>
//       <AppSidebar />
//       <main>
//         <SidebarTrigger />
//         {children}
//       </main>
//     </SidebarProvider>
//     </body>
//     </html>
//   )
// }


// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }
